### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by badplay** [ClementG91/Bot-presearch#1]
Hi have the bot auto login feature ??

some bots have this with cookie but after time the cookie is expiring so it will be nice if we can have a login feature thats input details automatic or renew the cookies if this can be done

i now some nice extensions to do the task for captcher like nopecha works great with the extension for browser alsow working with python

**Comment by ClementG91** [comment]
Hello, no there is no auto log function this and the first "bot" that I coded so there is only a little functionality, if you have any improvements I am interested, thank you for your feedback
