### ISSUE TITLE
{update} Auto text search

### ISSUE THREAD

**Issue by lolminerxmrig** [ClementG91/Bot-presearch#2]
hi.
plz add Auto text search or random keyword search.
pip install random_word

**Comment by ClementG91** [comment]
hi, 
it's done 👍 

https://github.com/ClementG91/Bot-presearch/blob/d14e79f426f5b513bc5efa51a84f4b9310bd1cf3/PreRandom.py

**Comment by lolminerxmrig** [comment]
can faster or multi browser open.
multi account?

**Comment by ClementG91** [comment]
no because there is a security that prevents too many requests in a short time I have already tried, but if you have a solution I am interested

**Comment by lolminerxmrig** [comment]
can talk telegram?

**Comment by ClementG91** [comment]
i dont have but if you want add me on discord ECorp#6345

**Comment by lolminerxmrig** [comment]
can make bot for : https://ouo.io/fQGhrB

**Comment by ClementG91** [comment]
maybe i can try but add me on discord it would be easier

**Comment by lolminerxmrig** [comment]
no have discord  accounts.

**Comment by ClementG91** [comment]
I'm a beginner I don't know yet how to use a proxy I still have to work

**Comment by lolminerxmrig** [comment]
can share email.
send user and pass

**Comment by lolminerxmrig** [comment]
send to : clement.genest91@laposte.net
